services:
  db:
    image: postgres:15
    container_name: blogmates_db
    restart: always
    environment:
      POSTGRES_DB: blogmates
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
