# Generated by Django 5.1.3 on 2025-01-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_friendship_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='friend',
            new_name='follower',
        ),
    ]
