# Generated by Django 5.2 on 2025-05-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_profile_picture_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
